NumPy, which stands for Numerical Python, is a library consisting of multidimensional array objects and a collection of routines for processing those arrays. Using NumPy, mathematical and logical operations on arrays can be performed. In this part, along with the basics of NumPy such as its architecture and environment, we shall also discuss the various array functions, types of indexing, etc.

We can install numpy by pip install numpy

Main object: ndarray

How do I create Arrays in Python?
Create an array from a regular Python list or tuple using the array function.

The type of the resulting array is deduced from the type of the elements in the sequences

It creates an ndarray from any object exposing array interface, or from any method that returns an array.

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 25.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [20]:
import numpy as np
# From list: 1d array 
my_list = [10, 20, 30]

my_array=np.array(my_list) # function np.array will help to convert python list to array
my_array

array([10, 20, 30])

In [23]:
# From list: 2d array

new_array = np.array([40, 50, 60])


my_2d_array = np.append(my_array, new_array, axis=0).reshape(2,-1) # This np.append function can be used to combine two array ,
                                                                    # in this python append cannot be used. Reshape() function determines rows and cols of the array 
                                                                    #  or can create a new shape as well 
                                                                    # axis = 0 means it will add or append row wise if axis=1 then it will append column wise


In [24]:
my_2d_array

array([[10, 20, 30],
       [40, 50, 60]])

In [33]:
new_col = np.array([100,200]).reshape(-1,1)
new_array = np.append(new_array,new_col, axis=1)


AxisError: axis 1 is out of bounds for array of dimension 1

In [34]:
my_2d_array

array([[10, 20, 30],
       [40, 50, 60]])

In [35]:
new_col = np.array([100, 200]).reshape(-1, 1)  # Shape (2,1)

In [36]:
my_2d_array = np.append(my_2d_array, new_col, axis=1)

In [37]:
my_2d_array

array([[ 10,  20,  30, 100],
       [ 40,  50,  60, 200]])

In [38]:
new_col

array([[100],
       [200]])

In [39]:
my_array

array([10, 20, 30])

In [40]:
my_array=np.append(my_array,100) # adding column to 1D

In [41]:
my_array

array([ 10,  20,  30, 100])

In [42]:
new_array = np.append(new_array,200) # adding column to 1D

In [43]:
new_array

array([ 40,  50,  60, 200])

In [44]:
my_2d2_array = np.append(my_array,new_array,axis=0).reshape(2,-1) # then appending two arrays with new column

In [45]:
my_2d2_array

array([[ 10,  20,  30, 100],
       [ 40,  50,  60, 200]])

In [46]:
my_2d2_array.shape # This will tell us dimesions of the array i.e no of row and column in each

##array([[ 10,  20,  30, 100] ---> row 1,4 columns
#       [ 40,  50,  60, 200] ----> row 2,4 columns])

(2, 4)

In [47]:
my_2d2_array.dtype # This will tell us the type 

dtype('int64')

In [53]:
# arrage ---> similar to range of python 

print(np.arange(0,10,1))
np.arange(0,10,3)

[0 1 2 3 4 5 6 7 8 9]


array([0, 3, 6, 9])

In [56]:
col = np.array([100,200]).reshape(2,1)

In [57]:
col

array([[100],
       [200]])

In [58]:
my_2d_array

array([[ 10,  20,  30, 100],
       [ 40,  50,  60, 200]])

In [59]:
my_2d_array = np.append(my_2d_array,col,axis=1).reshape(2,-1)

In [60]:
my_2d_array

array([[ 10,  20,  30, 100, 100],
       [ 40,  50,  60, 200, 200]])

In [61]:
np.random.randint(4, 40, 10)

array([35, 15, 13,  7, 34, 18, 24, 26, 29, 21], dtype=int32)

In [64]:
array_1=np.random.randint(4, 40, 10)

In [65]:
array_1

array([ 5, 24, 18, 24, 19, 17, 27, 20, 34, 11], dtype=int32)

In [69]:
arr=np.random.randint(50, size=(4,4))

In [68]:
array_1.tolist()

[5, 24, 18, 24, 19, 17, 27, 20, 34, 11]

In [70]:
arr.tolist()

[[28, 45, 16, 6], [26, 12, 33, 12], [8, 26, 34, 48], [31, 10, 0, 15]]